version: '2'
services:
  cassandra:
    extends: 
      file: ../cassandra/docker-compose.yml
      service: cassandra
    env_file: .env

  parser:
    extends:
      file: ../graphsense-blocksci/docker-compose.yml
      service: parser
    env_file: .env

  exporter:
    extends:
      file: ../graphsense-blocksci/docker-compose.yml
      service: exporter
    env_file: .env
    depends_on: 
    - cassandra

  transformation:
    extends:
      file: ../graphsense-transformation/docker-compose.yml
      service: transform
    env_file: 
     - .env
    depends_on: 
     - cassandra

networks:
  graphsense-global-net:
    external: true
